### ISSUE TITLE
(JS-0246) Require template literals instead of string concatenation

### ISSUE THREAD

**Issue by sasicodes** [lenstube-xyz/lenstube#124]
## Description
In ES2015 (ES6), we can use template literals instead of string concatenation.

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0246/occurrences/](https://deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0246/occurrences/)

**Comment by sasicodes** [comment]
@zt4ff Would you like to pick this up?

**Comment by zt4ff** [comment]
Yes @sasicodes
