### ISSUE TITLE
Make all basic info fields optional

### ISSUE THREAD

**Issue by sasicodes** [lenstube-xyz/lenstube#149]
Path - /settings

All the fields should be optional, users can leave it empty, but if it's filled the text should be validated like the current implementation.

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/29498872/193415608-90c73286-b641-41e9-9cbc-c6e64029946d.png">

**Comment by zt4ff** [comment]
Assign this to me
I am working on it right away
