### ISSUE TITLE
Fix search modal overflow in mobile view

### ISSUE THREAD

**Issue by sasicodes** [lenstube-xyz/lenstube#150]
<img width="360" alt="image" src="https://user-images.githubusercontent.com/29498872/193415667-26bf3b81-2975-4079-a4ac-ef668a603aff.png">

**Comment by Xaconi** [comment]
Hey, can I work on this one?

**Comment by sasicodes** [comment]
@Xaconi sure!

**Comment by Xaconi** [comment]
Not working! After a clean install and `npm run dev`, it shows me this error:

![image](https://user-images.githubusercontent.com/1944438/193417414-3752c52f-4a4f-48de-9121-f04ddfa53dfa.png)

Any advice @sasicodes ?

**Comment by sasicodes** [comment]
You need to add the RPC URL in .env `https://rpc.ankr.com/polygon_mumbai`
