### ISSUE TITLE
Fix delete page borders and backgroud colors in dark mode

### ISSUE THREAD

**Issue by sasicodes** [lenstube-xyz/lenstube#152]
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/29498872/193415957-6108eedd-83a3-40bb-9a64-747212323520.png">

**Comment by Xaconi** [comment]
Hey, can I work on this one?

**Comment by sasicodes** [comment]
@Xaconi still interested in working on this ser?

**Comment by Xaconi** [comment]
Nope, can't reproduce it in local.
