### ISSUE TITLE
(JS-0066) Shorthand type conversions are not preferred to use

### ISSUE THREAD

**Issue by sasicodes** [lenstube-xyz/lenstube#157]
## Description
In JavaScript, there are a lot of different ways to convert value types. Among these, implicit conversions can be hard to read and understand.

## Occurrences
There are 6 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0066/occurrences/](https://deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0066/occurrences/)

**Comment by utsav82** [comment]
So to solve the issue we have to remove any such short hand type conversions?
Can i take up this issue?
