### ISSUE TITLE
(JS-0229) Found an arrow function that could be confused for a comparison

### ISSUE THREAD

**Issue by sasicodes** [lenstube-xyz/lenstube#160]
## Description
Arrow functions (`=&gt;`) are similar in syntax to some comparison operators (`&gt;`, `&lt;`, `&lt;=`, and `&gt;=`). This rule warns against using the arrow function syntax in places where it could be confused with a comparison operator.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0229/occurrences/](https://deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0229/occurrences/)

**Comment by utsav82** [comment]
Can i be assigned to this?
