### ISSUE TITLE
Show loading state on change cover image in settings

### ISSUE THREAD

**Issue by sasicodes** [lenstube-xyz/lenstube#161]
Currently we won't see any loader until it uploaded to IPFS

![Image](https://user-images.githubusercontent.com/29498872/193448206-20600b74-7903-4e4c-b285-4f2544628d04.png)

**Comment by kala2** [comment]
hello can you assign to me please?

**Comment by kala2** [comment]
hey @sasicodes i have a question, is there a demo account to login and test the change of the cover image? because it says to connect wallet and i dont have any

**Comment by sasicodes** [comment]
Hey @kala2 , you should have a wallet. You can install the metamask browser extension and connect it to Polygon Mumbai. (Add Polygon Mumbai network in chainlist.org)


Also IPFS upload needs an estuary key in env,
you can try adding a loader and creating a PR, in the vercel preview we can test it because it has env configured .

I know this part for non web3 contributors is hard, will try to fix this.

**Comment by kala2** [comment]
hey @sasicodes thanks for the info. I want to push my changes and then proceed to a pull request. However, i got the following permissions issue regarding the git.

```
remote: Permission to lenstube-xyz/lenstube.git denied to themistoklis-bogiatzoglou.
fatal: unable to access 'https://github.com/lenstube-xyz/lenstube.git/': The requested URL returned error: 403
```

**Any ideas?**

**Comment by kala2** [comment]
hey @sasicodes, created a pull request #181

**Comment by sasicodes** [comment]
Done ✅
