### ISSUE TITLE
Fix username overflow in bytes

### ISSUE THREAD

**Issue by sasicodes** [lenstube-xyz/lenstube#164]
<img width="446" alt="image" src="https://user-images.githubusercontent.com/29498872/193457031-34b7e7f0-6c1f-4b78-8be5-b0d2095639ec.png">

**Comment by creativenull** [comment]
Hey!

I would like to help out with this, can I have a go at it?

**Comment by kala2** [comment]
hello if it's not assigned i can take this one too!

**Comment by sasicodes** [comment]
It's still open! Anyone can pick up 🙇🏻

**Comment by creativenull** [comment]
I just had a question regarding the username. Is there a character limit on the username when they register?

Because I would like to know if it would be a good idea to either truncate the letters or just wrap them instead so it doesn't overflow like show in the image.

**Comment by sasicodes** [comment]
@creativenull yes, the limit is 5 - 30 characters.

**Comment by creativenull** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/3767728/193881769-f703d15f-8ed7-4e40-815f-d77bd39dd010.png)

**Comment by sasicodes** [comment]
@creativenull yes, tailwind has a truncate class
