### ISSUE TITLE
Remove Accept Ownership checkbox in upload page

### ISSUE THREAD

**Issue by sasicodes** [lenstube-xyz/lenstube#165]
It's an extra step, we can remove that checkbox.

![Image](https://user-images.githubusercontent.com/29498872/193457657-2e39bb09-3de1-4273-a996-388e744f4ecc.png)

**Comment by ujwalkumar1995** [comment]
Hey. I can try to work on this. If I understood it correct, we need to remove the textbox along with the text right?

**Comment by sasicodes** [comment]
@ujwalkumar1995 Yes, remove the checkbox along with label from the form

**Comment by ujwalkumar1995** [comment]
Sure. I will submit a PR for this.

**Comment by ujwalkumar1995** [comment]
I have submitted below PR to fix this. Could you please review?
#166
