### ISSUE TITLE
Make connect wallet and sign in into a single-step process

### ISSUE THREAD

**Issue by benbaessler** [lenstube-xyz/lenstube#207]
Instead of having to click on the Sign In button after connecting a wallet, the application should automatically ask the user to sign in by signing a transaction.

**Comment by imranmahmudshoiball** [comment]
0xa1f40A36346E4Ef4c712C1e07F7E68e90b6b79C1

**Comment by sasicodes** [comment]
@benbaessler Adding a bounty for this!!!

**Comment by benbaessler** [comment]
> @benbaessler Adding a bounty for this!!!

Sorry for keeping this open! Please check the changes in the [PR](https://github.com/lenstube-xyz/lenstube/pull/227) and let me know if anything needs to be added/fixed, everything works as expected on my side. 🙂

**Comment by sasicodes** [comment]
https://polygonscan.com/tx/0x271279f991f6e9013586446eddb6504248ff6a8e2d173cd0d6cf90938b30b6ab
