### ISSUE TITLE
Notifications Page with All Notifications, Mentions, comments tabs

### ISSUE THREAD

**Issue by sasicodes** [lenstube-xyz/lenstube#211]
Instead of a popup, we should route to the `/notifications` page (we already have that page)

The notifications page should have two tabs,
1. All notifications
2. Mentions
3. Commented

Mentions filter - https://docs.lens.xyz/docs/users-notifications#api-details

**Comment by zt4ff** [comment]
Can you assign this to me @sasicodes

**Comment by zt4ff** [comment]
I have been away to health for a while
I have started working on it

**Comment by sasicodes** [comment]
thanks for the update @zt4ff 🙇🏻

**Comment by zt4ff** [comment]
> Instead of a popup, we should route to the `/notifications` page (we already have that page)
> 
> The notifications page should have two tabs,
> 
> 1. All notifications
> 2. Mentions
> 3. Commented
> 
> Mentions filter - https://docs.lens.xyz/docs/users-notifications#api-details

@sasicodes, can you explain a bit more about this? The previous notification page had 6 tabs and you want it to be reduced to two - Commented and Mentions?

**Comment by sasicodes** [comment]
@zt4ff currently we combined all the notifications in one tab, we wanna have a page in web view (there is already a notifications page for mobile view, we can reuse).

we wanna split the notifications category into All | Comments | Mentions (its enough for now)

we can do this using `notificationTypes` filter - https://docs.lens.xyz/docs/users-notifications#api-details

**Comment by sasicodes** [comment]
https://github.com/lenstube-xyz/lenstube/pull/327
