### ISSUE TITLE
(JS-0323) Detected usage of the `any` type

### ISSUE THREAD

**Issue by sasicodes** [lenstube-xyz/lenstube#24]
## Description
The `any` type can sometimes leak into your codebase. TypeScript compiler skips the type checking of the `any` typed variables, so it creates a potential safety hole, and source of bugs in your codebase. We recommend using `unknown` or `never` type variable.

## Occurrences
There are 44 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0323/occurrences/](https://deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0323/occurrences/)

**Comment by zt4ff** [comment]
Assign me to this please @sasicodes
