### ISSUE TITLE
make meta tag "title" show name of video

### ISSUE THREAD

**Issue by mega7mega** [lenstube-xyz/lenstube#255]
make meta tag "title" show name of video
righr now title just says "lenstube" would be really good if it were the real title of the video

**Comment by sasicodes** [comment]
gm! you mean in social cards?

**Comment by mega7mega** [comment]
![image](https://user-images.githubusercontent.com/114383396/198294087-ab2d721d-c134-461b-83b9-59ffa80d63c7.png)

all them. standard title tag, meta title tag, card title tag
this way google would properly index the videos bringing in tons of traffic :-)

**Comment by sasicodes** [comment]
We have implemented it for the channel and video page.
