### ISSUE TITLE
Optimistic Post

### ISSUE THREAD

**Issue by sasicodes** [lenstube-xyz/lenstube#275]
We can show a share modal after the post redirect on the profile page.

- We get `txId` of the publication yet to be indexed, using that we can poll in the same modal still indexed.
- Then we can ask to share any social media intents.

**Comment by zt4ff** [comment]
Can you assign this to me? @sasicodes

**Comment by sasicodes** [comment]
> Can you assign this to me? @sasicodes

After a successful post, we get only the transaction hash, which we need to poll and get the publication details once mined. The modal can have a loader indicating indexing and after that, we can show external links to share like twitter son on.
