### ISSUE TITLE
(JS-0749) Prefer to have a unique title in `<iframe>`

### ISSUE THREAD

**Issue by sasicodes** [lenstube-xyz/lenstube#366]
## Description
`&lt;iframe&gt;` elements must have a unique title property to indicate its content to the user.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0749/occurrences/](https://deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0749/occurrences/)

**Comment by zt4ff** [comment]
@sasicodes 
You can assign this to me please?

**Comment by zt4ff** [comment]
@sasicodes 
I already made a PR

I need your opinion please, can I DM in Discord?

**Comment by sasicodes** [comment]
> @sasicodes I already made a PR
> 
> I need your opinion please, can I DM in Discord?

sure
