### ISSUE TITLE
(JS-0339) Found non-null assertions

### ISSUE THREAD

**Issue by sasicodes** [lenstube-xyz/lenstube#368]
## Description
Using non-null assertions cancels the benefits of the strict null-checking mode.

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0339/occurrences/](https://deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0339/occurrences/)

**Comment by zt4ff** [comment]
@sasicodes 
You can assign this to me please.

**Comment by zt4ff** [comment]
@sasicodes

**Comment by sasicodes** [comment]
@zt4ff There is a deployment error on the PR, can you address it? 🙇🏻

**Comment by zt4ff** [comment]
Yeah, I will
