### ISSUE TITLE
(JS-0378) Found template literal expression having a non-string type

### ISSUE THREAD

**Issue by sasicodes** [lenstube-xyz/lenstube#370]
## Description
Using only string values in placeholders is recommended as otherwise, the value may be wrongly displayed; for example, if an object value is directly included in a string, it will be shown as `[object Object]`. Using only string values can also ensure that `null` or `undefined` values are not directly …

## Occurrences
There are 4 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0378/occurrences/](https://deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0378/occurrences/)

**Comment by zt4ff** [comment]
Hi @sasicodes 

Checking the link now it says no result found. I guess it's fixed?

![2022-11-23_09-47](https://user-images.githubusercontent.com/61902277/203504161-fde80819-9975-4856-9f71-e09f71ccd64a.png)

**Comment by sasicodes** [comment]
@zt4ff yes. will close this!
