### ISSUE TITLE
(JS-0765) Prefer that non-interactive, visible elements (such as <div>) that have click handlers use the role attribute

### ISSUE THREAD

**Issue by sasicodes** [lenstube-xyz/lenstube#371]
## Description
Static HTML elements do not have semantic meaning. This is clear in the case of `&lt;div&gt;` and `&lt;span&gt;`. It is less so clear in the case of elements that _seem_ semantic, but that do not have a semantic mapping in the accessibility layer. For example `&lt;a&gt;`, `&lt;big&gt;`, `&lt;blockquote&gt;`, `&lt;footer&gt;`, `&lt;picture&gt;`, …

## Occurrences
There are 13 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0765/occurrences/](https://deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0765/occurrences/)

**Comment by zt4ff** [comment]
Hi @sasicodes 
Can you assign this to me?
