### ISSUE TITLE
Bug (with solution PR): Video Category's Chevron Icons update late based on click event

### ISSUE THREAD

**Issue by abhiram11** [lenstube-xyz/lenstube#628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Note: I have also issued a Pull Request based on this Bug, please consider it after inspecting this bug report. Thanks!

The Category scroll bar does not update (hide/show) its `ChevronRightOutline` or `ChevronLeftOutline` as scrolling is done by updating the `useRef`.

Here's how the UI Normally looks:
![Issue](https://user-images.githubusercontent.com/20269286/219800792-be35606a-afaf-4b4f-b173-e4818a957fb6.JPG)

Here's how it looks after we click on `>` ONCE, the Red box indicates that the `<` icon should already be visible now:
![Issue1](https://user-images.githubusercontent.com/20269286/219800898-d449437e-2bcb-416d-8823-f7247d7f4063.JPG)

Here's how it looks RIGHT AFTER we reach the end of the scroll list, the red box indicates that the `>` icon should already disappear now:
![Issue2](https://user-images.githubusercontent.com/20269286/219801027-32f543a2-dfcd-4d7d-b5a4-1ae6a5ee031a.JPG)

### Expected Behavior

The expected behavior **(as also shown as a solution in my PR)** is that the `<` and `>` icons are displayed correctly and not after one more (unnecessary) click event to be done to update/re-render the UI.

## This is how the proposed solution in my PR looks like:
**The URL shows the difference between the current behavior (lenstube) and the expected behavior (localhost)**

https://user-images.githubusercontent.com/20269286/219801637-929afbb0-0477-4449-b05b-8a4f7b84fa75.mp4

### Steps To Reproduce

The original website currently shows the same behavior, kindly click on the `>` and `<` of the category section to see the bug.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by sasicodes** [comment]
Great catch!
