### ISSUE TITLE
 Add Lensplay app-id: lensplay to Lenstube data fetching queries

### ISSUE THREAD

**Issue by VIVEK-SUTHAR** [lenstube-xyz/lenstube#750]
### Describe the feature you'd like to request

We have noticed that videos uploaded via [Lensplay](https://lensplay.xyz) are not being reflected on Lenstube. After investigating, we realized that the Lensplay app-id is not currently being included in the data fetching queries for Lenstube.

LensPlay's App ID is `lensplay`.

So it is our humble request to you to include Lensplay app-id in data fetching queries.

**Comment by VIVEK-SUTHAR** [comment]
https://ys3cf5twtuotpi4xab3z67twlt5da7jl5ac4jluz7cu3ij3qt4zq.arweave.net/xLYi9nadHTejlwB3n352XPowfSvoBcSumfiptCdwnzM 
Here's the metadata link.

**Comment by sasicodes** [comment]
Looks good ✅  Will add!
