### ISSUE TITLE
[Feature Request] Add item count to comment section

### ISSUE THREAD

**Issue by benbaessler** [lenstube-xyz/lenstube#813]
### Describe the feature you'd like to request

It would be nice to display the number of comments there are under a video. This is how it currently looks: 

<img width="1005" alt="Screenshot 2023-04-29 at 15 11 32" src="https://user-images.githubusercontent.com/78696428/235307414-1879650d-f1af-4f93-b743-77f2aa1a01d3.png">

**Comment by sasicodes** [comment]
`totalCount` is deprecated for performance reasons in API. we ll plan on it.
