### ISSUE TITLE
View count does not work

### ISSUE THREAD

**Issue by benbaessler** [lenstube-xyz/lenstube#814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Under any video, the view count always displays 0.

### Expected Behavior

Should be the correct view count.

### Steps To Reproduce

Navigate to any publication on Lenstube.

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome

**Comment by sasicodes** [comment]
we are working on fixing this!

**Comment by sasicodes** [comment]
this should be fixed now. Let us know if you face anything! thanks for raising it!
