### ISSUE TITLE
Requesting to add 'diversehq' appId to ALLOWED_APP_IDS for DiverseHQ

### ISSUE THREAD

**Issue by RathodDeven** [lenstube-xyz/lenstube#831]
### Describe the feature you'd like to request

Hi, Sasi! I am unsure if any requirements must be fulfilled to be eligible to be added to the ALLOWED_APP_IDS. If there are any please let me know, else requesting to add the 'diversehq' appId to the ALLOWED_APP_IDS. Thanks 🙌.

Here is a metadata link : https://gateway.ipfscdn.io/ipfs/QmTRv7KRixYrHqrHaR38vg7fqn79T8HmxwUqm6EYYaLBxL/

**Comment by sasicodes** [comment]
`durationInSeconds` is missing in attributes 🙇🏻

**Comment by sasicodes** [comment]
is it possible to add a thumbnail for the video, in cover or image key?

**Comment by RathodDeven** [comment]
> is it possible to add a thumbnail for the video, in cover or image key?

Yes, will be deploying ability to choose thumbnail soon.

**Comment by RathodDeven** [comment]
> is it possible to add a thumbnail for the video, in cover or image key?

Hey, just deployed the required changes, now there will be a thumbnail image in image key... 
If there is still anything else please let me know

**Comment by sasicodes** [comment]
looks good. you can add `cover` in the media object itself to indicate that's cover of the media is attached 🙇🏻 

```
  "media": [
    {
      "item": "ipfs://bafybeidvy5rnnsx5sg2hdxivgrbmp5r2owdu2zxdpg7pb4nwwb7t3xozyi",
      "type": "video/mp4",
      "cover": "ipfs://bafybeici3z735c7od2augh7nlmaugq3ruzu4ytlqntjcb5dk2j4x4ixp3m"
    }
  ],
```

https://arweave.app/tx/jPX23KK8cq_Us0RMpqXcuZOoiZuksG5-9j4DmKKUPHg

**Comment by RathodDeven** [comment]
> looks good. you can add `cover` in the media object itself to indicate that's cover of the media is attached 🙇🏻
> 
> ```
>   "media": [
>     {
>       "item": "ipfs://bafybeidvy5rnnsx5sg2hdxivgrbmp5r2owdu2zxdpg7pb4nwwb7t3xozyi",
>       "type": "video/mp4",
>       "cover": "ipfs://bafybeici3z735c7od2augh7nlmaugq3ruzu4ytlqntjcb5dk2j4x4ixp3m"
>     }
>   ],
> ```
> 
> https://arweave.app/tx/jPX23KK8cq_Us0RMpqXcuZOoiZuksG5-9j4DmKKUPHg

Aaha thanks, added this as well in the cover 

https://gateway.ipfscdn.io/ipfs/QmTUr9TVouuSbaULu9pkCke7ViaBFonQsZykjMMupWKecP/

**Comment by RathodDeven** [comment]
Hey, any updates ..?

**Comment by RathodDeven** [comment]
Thanks a lot, Sassi!
